# name: Continuous Integration

# on:
#   pull_request:
#     branches: [main]
#   push:
#     branches: [main]

# permissions:
#   contents: read

# jobs:
#   format:
#     name: Formatting
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version-file: ".python-version"
#       - name: Install the latest version of uv
#         uses: astral-sh/setup-uv@v6
#       - name: Set up shfmt
#         uses: mfinelli/setup-shfmt@v3
#       - name: Check formatting
#         run: |
#           ./scripts/format.sh

#   tests:
#     name: Tests
#     runs-on: ubuntu-latest
#     needs: format

#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version-file: ".python-version"
#       - name: Install the latest version of uv
#         uses: astral-sh/setup-uv@v6
#       - name: Run tests
#         run: |
#           scripts/test.sh
